### ISSUE TITLE
isSuccess is always true when createOrUpdateEvent

### ISSUE THREAD

**Issue by ghost** [builttoroam/device_calendar#170]
Hi everyone, 

I'm using the latest version 3.0.0+3. I'm actually testing the application with the iOS emulator on my mac with all the updated versions and a standard google account.

I need to create about 350 events in the calendar from the application, but not all events are created in Google Calendar.  The creation always returns true in isSuccess() and an eventID on date. If I look at the online calendar not all the events have been created, while if I try to delete all the records just created (via eventId returned from the creation), many deletions return an error.

```
Result<String> ris = await DeviceCalendarPlugin().createOrUpdateEvent(e);
Result<bool> ris = await DeviceCalendarPlugin().deleteEvent(widget.calendar.getCalendarId, s);
```

If I set a delay between each creation, it is very likely that all events are created, but this is not a security.

`await Future.delayed(const Duration(milliseconds: 250));`

**Comment by Brett09** [comment]
Not exactly sure what's going on there, will need to do some testing to see what's happening. Meanwhile, have you tried the same actions on an Android device?

**Comment by Gitminh9201** [comment]
Same! All event i try create return 'success' but not some item can go it :((((

**Comment by Brett09** [comment]
@Gitminh9201, how many events were you creating and (roughly) how many didn't get created?

**Comment by cptloc** [comment]
As i told about 350 events added and from 200 to 250 created. It's always the same. Uf I put a delay between each add (about 500 milliseconds) all events are created successfully.
How I check if all events are created? I save all events id and then I delete it from GCal.

In the next few days I will try with Android to see If I have the same problem, but I can try only with the simulator.

**Comment by Brett09** [comment]
I've just tested creating 350 events (by looping) in both platforms all of them were added successfully - it returns all true for `isSuccess` and I could see `retrieveEvents` method was returning all 350 events. 
But I get the same issue on deleting them, where roughly half of them gets deleted.

I've put a delay of 10 milliseconds for each iteration (`await Future.delayed(Duration(milliseconds: 10));`) and I could see everything working fine.
I don't see much of a problem using a short delay here, so I would recommened to use the delay to avoid this issue.

As a side note, all of the plugin method uses platform-specific code (found [here](https://flutter.dev/docs/development/platform-integration/platform-channels?tab=ios-channel-swift-tab)), where sending a message and receiving a callback in a big loop could cause the issue (this is just my assumption so I could be wrong).

**Comment by cptloc** [comment]
Hi, isSuccess always returns true to me too, but if I check online on Google calendar I don't see all the events, and when I go to delete them it returns an error on the events it doesn't find.

A delay of 10 milliseconds is not enough for me, the entry is not always successfully created, I found that 250 guarantees me, at least for the tests I did, that all the events are created correctly (I can delete them without error).

**Comment by andzejsw** [comment]
Does error still exists on latest dev?
