### ISSUE TITLE
On Android calendars are return in a map <key, value>

### ISSUE THREAD

**Issue by flenair** [builttoroam/device_calendar#211]
Hello,
On Android (device or simulator) in my application when I retrieve the calendar list I always have a map (key-value) and not a list of calendars. Work's fine on Ios.

When I'm using the sample app, I have not this problem.

![image](https://user-images.githubusercontent.com/38036065/77892142-62581780-7272-11ea-9b12-941eeab2f2dc.png)

Maybe a setting android of my projet, but which one ? It's not a problem of permission.
Thx for help

Using device_calendar: 3.1.0, I've also tried 2.0.0

**Comment by Brett09** [comment]
How are you retrieving calendars? Are you using `retrieveCalendars` in `device_calendar.dart`? That output doesn't seem like a calendar at all.

**Comment by flenair** [comment]
Yes that's what i did.
The example projet is working fine, so i decided to take all src files inside my project.
And it doesn't work, same problem
I tried also to find an android setting that could be different and the root cause but i still dont find.
I've also tried tu used the same version of gradle...Same problem.

**Comment by nickrandolph** [comment]
@flenair are you trying to access the same calendar in both the sample app and your app? It seems bizarre that you're seeing different results in your app v the sample app.

**Comment by flenair** [comment]
I found the problem, but i can't explain it.
The plugin doesn't work when we have 2 buildTypes in the build.gradle in the project

buildTypes {
        release {
            signingConfig signingConfigs.release
            ...
        }
        /*debug {
            ....
        }*/
    }
