### ISSUE TITLE
Is there a way to delete a calendar?

### ISSUE THREAD

**Issue by mcavazotti** [builttoroam/device_calendar#225]
I couldn't find anything about it in the docs. I just need to be able to delete the calendars created by this plugin

**Comment by dabellana07** [comment]
same, I need this feature too and would be nice to have it.

**Comment by Ananthan1996** [comment]
Yes it's there .but I am facing some issue in android release mode while deleting events .It is working fine in debug mode.

**Comment by marcusaram** [comment]
Same issue here, should have a way to delete the calendar to clean things up again if user wants it.

**Comment by nickrandolph** [comment]
Feel free to contribute a PR to add this. Otherwise it'll get added to the backlog

**Comment by elleryq** [comment]
I find a way to delete local calendar manually.


    Settings > Apps & Notifications > See all Apps > (... menu) Show System
    Navigate to "Calendar Storage", choose Storage & cache, and then Clear storage.
    All calendar events will disappear, sync'd events will repopulate via account sync over the next few minutes.

https://android.stackexchange.com/questions/24789/how-do-i-delete-a-single-calendar-in-android-not-just-hide-it
