### ISSUE TITLE
Event reminder is not updating in iOS.

### ISSUE THREAD

**Issue by ssivagnanam** [builttoroam/device_calendar#227]
Hi team,

I have created an event with reminder duration as 0 minutes (which is at the time of event).  And later on when i tried to change it from 0 to XX minutes.  It not updating in device calendar.  This issue occurs only in iOS devices.

Code snippet:
 Event _event = new Event(writableCalendarId,
              eventId: shift.localShiftId != "0" ? shift.localShiftId : null);
          _event.title = AppStrings.REMINDER_TITLE;
          _event.start = shift.startDate;
          _event.end = shift.endDate;
          _event.description =
              "Help message";
          _event.reminders = [
            new Reminder(minutes: ConfigUtil.getReminderTime())
          ];
          _event.location = shift.storeName;
          _event.allDay = false;

          var result = await _deviceCalendarPlugin.createOrUpdateEvent(_event);

Please let me know the work around for this.

**Comment by nickrandolph** [comment]
@ssivagnanam to help diagnose this
- Can you confirm that if you create an event with reminder at XX minutes, it does indeed work?
- If you updated other aspects of the event, do they get updated?

**Comment by ssivagnanam** [comment]
Hi, 
Yes.  All other properties are getting reflected in Device calendar reminder. 
Only with the above scenario, my device calendar reminder is not reflecting reminder time properly.

**Comment by ssivagnanam** [comment]
@nickrandolph Any update on this?

**Comment by SuperKrallan** [comment]
There is something fishy going on with the loading of reminders. I use iOS 15.4. An event saved in iOS Calendar with a reminder, then accessed with device_calendar like  _print('Reminders: ' + event.reminders.toString());_ returns _Reminders: []_, but all other data in the event is loading ok. Saving a reminder using device_calendar works fine and is visible in the iOS Calendar, but accessing it using device_calendar returns [].

**Comment by thomassth** [comment]
This might be a bug but I'm not sure

Are you using the latest version?

**Comment by SuperKrallan** [comment]
If the question was directed at me so yes, 4.2.0.

**Comment by SuperKrallan** [comment]
Same error with saved reminders not getting loaded into flutter app using device_calendar on android emulator.  So both iOS and Android affected it seems. I have had a quick look at the flutter code loading events, but no obvious errors that I can see (but I am no expert...).

**Comment by SuperKrallan** [comment]
Did some further digging, and the error was on my side. Removing my above comments in order not to cause confusion. I apologise. (I am indeed not an expert...)
