### ISSUE TITLE
I want a default calendar for my flutter app through which i will be able to add,delete events in my device

### ISSUE THREAD

**Issue by elaishane** [builttoroam/device_calendar#228]
Can you do something to allow me to use one default calendar in my flutter app. its urgent

**Comment by nickrandolph** [comment]
@elaishane you should be able to access the default device calendar using this plugin. Can you provide more context:
- What device (android or ios) are you using?
- What calendars do you see when you get the list of calendars?

**Comment by elaishane** [comment]
Well I the solution

**Comment by elhamadjidi** [comment]
Hi,
I need to add events to the default calendar; I don't want to show a list to the user; to define an event object it needs the calendar id, what should I put there?

**Comment by elhamadjidi** [comment]
@nickrandolph

**Comment by elhamadjidi** [comment]
@elaishane how could you solve your problem?

**Comment by leonid-demyanenko** [comment]
Any solution to this case? If facing it too.

**Comment by IVLIVS-III** [comment]
Using this plugin, you can retrieve a list of **all** device default calendars. In most cases there will be more than one default calendar.
Each calendar object in this list also has its corresponding calendar id as a read-only attribute, which you can use to add events.

If you don't want to ask the user about which of the multiple default calendars to use when adding the event, you will have to choose on behalf of the user.

A sample algorithm to choose a default calendar without user intervention would be to filter the list by those calendars which allow read-write access and then choose the first calendar.
But keep in mind that users might expect to have a choice on their own of which calendar to add the event to. This all depends on your use case.
