### ISSUE TITLE
Event not deleting from Google calendar ( Android release mode)

### ISSUE THREAD

**Issue by Ananthan1996** [builttoroam/device_calendar#229]
Event is not deleting in Google calendar when the flutter app is run in release mode.Both creation and deletion is working in debug mode.But only creation is working on release mode.Please help me to find solution inorder to delete the event in release mode.I have to release one urgent feature

**Comment by Ananthan1996** [comment]
Create/update is working fine in release mode.

**Comment by nickrandolph** [comment]
@Ananthan1996 Can you provide more information please:
- What device are you running on?
- What calendar account type are you using (Office 365, Gmail, Local device calendar)?
- Are you seeing this issue on iOS too?

**Comment by 2math** [comment]
Hi, first than you for this great plugin!

I face the same issue in debug mode.
Testing on Pixel 3a XL, haven't tested yet on iOS.
I'm using Google Calendar, I think there is some delay from Google calendar too, but when I add event it appears in a minute.
Deleting an event goes without error, when I query for this event or in this period the event is not returned, but when I open Google calendar is still there :( .

Need to investigate if Google calendar has it self some restrictions for deleting events from other apps by the API , which will be non sense, but I have seen even worse.

**Comment by andzejsw** [comment]
> Here is something weird, I was trying to delete 100+ events and just now saw a notification from Google Calendar app that was saying
> _"You are trying to delete too many items (108) from calendar. What do you want to do"_
> **Delete them all** | **Undo** | **Do nothing for now**
> 
> After clicked on **Delete them all** they disappeared form the calendar, inserting and deleting single event works too now, I guess the calendar was blocked before that

So delete function now works for you correctly? Can you confirm?

**Comment by 2math** [comment]
Confirm
