### ISSUE TITLE
i dont get url in google calender.

### ISSUE THREAD

**Issue by jayeshpansheriya** [builttoroam/device_calendar#234]
i have make demo of calendar project from [https://github.com/builttoroam/device_calendar/tree/develop/example](url)
but currently i make any new event in android device then i see in google calendar app its not show any url.
**android device project screenshot**
![Screenshot_1591180092](https://user-images.githubusercontent.com/31765271/83626448-0fbd1380-a5b3-11ea-9d59-2139201e39e1.png)

**android device calendar app screenshot**
![Screenshot_1591180155](https://user-images.githubusercontent.com/31765271/83626540-324f2c80-a5b3-11ea-9f3f-7ed0e9cb43bd.png)

**ios device calendar screenshot**
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-06-03 at 16 00 22](https://user-images.githubusercontent.com/31765271/83626647-5dd21700-a5b3-11ea-8310-ed6b772b4de7.png)

**calendar screenshot from website**
![Screenshot 2020-06-03 at 4 01 49 PM](https://user-images.githubusercontent.com/31765271/83626782-91ad3c80-a5b3-11ea-9997-a056381323b6.png)

i dont get any url from google calendar web or android device google calendar app like ios app calendar.

**Comment by nickrandolph** [comment]
@jayeshpansheriya are you using the same account on all three platforms (ie ios, android and web)? 
If you create the event on ios (via the plugin), does the url show up on web and/or android?
If you create the event on android (via the plugin), does the url show up on web and/or ios?

**Comment by jayeshpansheriya** [comment]
@nickrandolph    yes i have used same account for all,
yes if i created event via plugin in android or ios device  all detail shows but meeting url is not show in google calendar website, i have shared screenshot above.

**Comment by nickrandolph** [comment]
@jayeshpansheriya is that not just a limitation of the google calendar app? Do you have an example of where a url is shown in the google calendar app?
