### ISSUE TITLE
PlatformException Events.availability on Android

### ISSUE THREAD

**Issue by imhafeez** [builttoroam/device_calendar#241]
When adding events on Android it throws the following error. could anyone please help?

` PlatformException(500, NOT NULL constraint failed: Events.availability (code 1299 SQLITE_CONSTRAINT_NOTNULL), null)`

**Comment by nickrandolph** [comment]
@imhafeez which version of the package are you using?

**Comment by imhafeez** [comment]
I am using `device_calendar: ^3.1.0`

**Comment by nickrandolph** [comment]
Can you check which version the .lock file says is being referenced. If still 3.1, can you try the Dev release of 3.2

**Comment by imhafeez** [comment]
<img width="467" alt="Screenshot 2020-06-21 at 1 59 54 PM" src="https://user-images.githubusercontent.com/21155655/85220737-8a659b80-b3c7-11ea-9280-b3550ccf1020.png">

**Comment by andzejsw** [comment]
@imhafeez does this error exist on latest dev?

**Comment by imhafeez** [comment]
@andzejsw Yes its still accurring. On updating event.

`Exception has occurred.
PlatformException (PlatformException(500, NOT NULL constraint failed: Events.availability (code 1299)
#################################################################
Error Code : 1299 (SQLITE_CONSTRAINT_NOTNULL)
Caused By : Abort due to constraint violation.
	(NOT NULL constraint failed: Events.availability (code 1299))
#################################################################, null, null))`

**Comment by andzejsw** [comment]
@imhafeez Is this happening on example app?

**Comment by andzejsw** [comment]
Events also have availability arg. Are you sure that when you crate it, it isn't null?

**Comment by imhafeez** [comment]
@andzejsw Let me check that.

**Comment by imhafeez** [comment]
Thanks @andzejsw. It was availability arg. I was not setting that. It solved.

Also on the device it throws exception on creating calendar. The issue is with calendar colour. I have changed it. and will send you pull request. Please merge it with master branch.

**Comment by andzejsw** [comment]
@imhafeez I will add changes, that availability should be required.
