### ISSUE TITLE
Remove duplicate line code from event.dart

### ISSUE THREAD

**Issue by carlosDigio** [builttoroam/device_calendar#246]
Hi @nickrandolph, please can you remove from last code this duplicate line from event.dart model? 

https://github.com/builttoroam/device_calendar/blob/fe932a1ce3b36c9d0a2659d2abd65635c26a33fd/lib/src/models/event.dart#L127

The correct line is L91:

https://github.com/builttoroam/device_calendar/blob/fe932a1ce3b36c9d0a2659d2abd65635c26a33fd/lib/src/models/event.dart#L91

Or is it necessary to create a new PR?

Sorry for the inconvenience
Thanks a lot

**Comment by nickrandolph** [comment]
Argh, must have been a bad rebase. Do you mind raising a quick PR and I'll approve.

**Comment by carlosDigio** [comment]
Done. https://github.com/builttoroam/device_calendar/pull/247 Thanks!
