### ISSUE TITLE
Change Android Integration on pub.dev

### ISSUE THREAD

**Issue by Plateria** [builttoroam/device_calendar#250]
I had the issue, that when i built a release version of my app containing the device_calendar plugin, the retrieve_calendars() function didn't work at all. After finding the solution to my problem [#99 ](https://github.com/builttoroam/device_calendar/issues/99#issuecomment-612449677) i suggest that you should add the following to [pub.dev/device_calendar#android-integration](https://pub.dev/packages/device_calendar#android-integration), because you have to add the proguard rule anyways to make it work.

> android/app/proguard-rules.pro
> Mine looks like this:
> 
> `#Flutter Wrapper`
> `-keep class io.flutter.app.** { *; }`
> `-keep class io.flutter.plugin.**  { *; }`
> `-keep class io.flutter.util.**  { *; }`
> `-keep class io.flutter.view.**  { *; }`
> `-keep class io.flutter.**  { *; }`
> `-keep class io.flutter.plugins.**  { *; }`
> 
> `# You might not be using firebase`
> `# -keep class com.google.firebase.** { *; }`
> `-keep class com.builttoroam.devicecalendar.** { *; }`
> 
> then in android/app/build.gradle add the following line to buildTypes { release {}}
> proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
> 
> I also use minifyEnabled true and shrinkResources true in the same place.
> 
> Finally under android/gradle.properties I have android.enableR8=true, R8 still respects your proguard rules.

This solution is copied from [here](https://github.com/builttoroam/device_calendar/issues/99#issuecomment-612449677)

**Comment by nickrandolph** [comment]
An you check the readme (https://github.com/builttoroam/device_calendar) and if changes required, please submit a pr. I will check what's being published to pub.dev and update that when I can.

Thanks

**Comment by Plateria** [comment]
Yea i checked the README. My suggestion is to change:

> If you have Proguard enabled, you may need to add the following to your configuration (thanks to Britannio Jarrett who posted about it here)

to:

> If you want to release the app, you have to enable proguard and follow these steps...

**Comment by jurgenramirez** [comment]
I compiled the application with flutter build apk --release and it did not have any proguard file I followed the steps mentioned but it does not work it still does not write to the calendar, from the emulator it works but when I install the apk on a device it does not work, help please.

**Comment by Plateria** [comment]
@jurgenramirez Which steps did you exactly do?
