### ISSUE TITLE
Module 'device_calendar' not found when Release iOS for Distribution

### ISSUE THREAD

**Issue by digarahayu** [builttoroam/device_calendar#254]
When i try to distribution my app following step from https://flutter.dev/docs/deployment/ios, i got error Module 'device_calendar' not found on step 'Select Product > Archive to produce a build archive.'
<img width="1209" alt="Screen Shot 2020-08-03 at 09 55 16" src="https://user-images.githubusercontent.com/23516065/89141676-7472fb00-d56f-11ea-9814-e7b727c80934.png">

maybe is there step that i miss..?

thanks for replay

**Comment by natheemy** [comment]
Please let me know what are the workaround or changes to fix this issue?
