### ISSUE TITLE
Error messages not very useful

### ISSUE THREAD

**Issue by ShannonHall** [builttoroam/device_calendar#260]
Exceptions are intercepted and passed into `Result.errorMessages`. This makes it very hard to get the error and deliver meaningful messages to the user.

Example:
This is the Error message delivered after the user has denied access and we try to modify the calendar -

`[599] Device calendar plugin ran into an issue. Platform specific exception [401], with message :"The user has not allowed this application to modify their calendar(s)", has been thrown`
It comes in the form of a `String` which is useless if we want to deliver a meaningful message to the user.
It would be nice to be able to tell the user if they want to use the feature they need to allow permission and how to do that etc, but with the exception being parsed how it is this is very difficult.

If we get the untouched `PlatformException` we can check the code and deliver a message to the user based on that or in some cases just forward the message.

**Comment by MeherBa** [comment]
How to handle this exception in iOs ?

**Comment by andzejsw** [comment]
You can use `errorCode` from ResultError class to display specific error messages for specific error code.
