### ISSUE TITLE
Delete created calendar

### ISSUE THREAD

**Issue by mees-brenzie** [builttoroam/device_calendar#263]
Hi all!

I have a very short question: is it possible to delete any created calendars? I have not found anything in the documentation. I've not even been able to delete the calendars manually. Am I missing something?

Thanks in advance!

**Comment by tovidd** [comment]
i faced same issue, but i see it possible on example project

**Comment by tovidd** [comment]
> Hi all!
> 
> I have a very short question: is it possible to delete any created calendars? I have not found anything in the documentation. I've not even been able to delete the calendars manually. Am I missing something?
> 
> Thanks in advance!

You are able to delete calendar using prerelease version (https://pub.dev/packages/device_calendar/versions/3.2.0-dev.12672)
currently available version (device_calendar: ^3.2.0-dev.12672)
