### ISSUE TITLE
'String' is not a subtype of type 'Availability'

### ISSUE THREAD

**Issue by mees-brenzie** [builttoroam/device_calendar#264]
Hi!
I'm getting a weird, unexpected error.

Once I retrieved a list with events, It crashes on everything I try to do with any item in this list. Not even print the id of the first element. The retrieving of the events causes no issues, printing the length of the list works fine, but everything after that does. It seems that something is going wrong with the decoding of the 'availability' variable from JSON. But I'm not quite sure why that would happen since I'm trying to access the actual Event object from the list, returned by the retrieveEvents method. 

Please help...

code:
```
var result = await plugin.retrieveEvents(calendarId, params);
    var list = result?.data;
    if (list != null) print(list.first.eventId); <-- causes crash
```

error:
```
E/flutter ( 3903): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: type 'String' is not a subtype of type 'Availability'

E/flutter ( 3903): #0      new Event.fromJson - package:device_calendar/…/models/event.dart:127

E/flutter ( 3903): #1      DeviceCalendarPlugin.retrieveEvents.<anonymous closure>.<anonymous closure> -  package:device_calendar/src/device_calendar.dart:110

E/flutter ( 3903): #2      MappedListIterable.elementAt  (dart:_internal/iterable.dart:417:31))

E/flutter ( 3903): #3      UnmodifiableListView.[]  (dart:collection/collections.dart:23:39))

E/flutter ( 3903): #4      ListMixin.first  (dart:collection/list.dart:100:16))
```

**Comment by pdtoal** [comment]
I am using a slightly modified version of the example app that comes with the plugin (3.2.0-dev.11640) and i'm getting exactly the same error when I deploy my app in debug mode to my iPhone XR running iOS 14. If I deploy the same app to the same device/OS on the simulator I don't see the problem.

**Comment by mees-brenzie** [comment]
@nickrandolph Is there any information on this? This is kind of a big error and prevents us us from using this library all together

**Comment by andzejsw** [comment]
@mees-brenzie is this issue still for you with latest dev version?
