### ISSUE TITLE
Color events

### ISSUE THREAD

**Issue by mostal69** [builttoroam/device_calendar#265]
Hello

I would like to get colorId for each events

Do u know if it would be possible in next releases please ?

Tried to changed events.dart on your lib but no colorId always null even for events with color defined (other than default color)

Regards

**Comment by andzejsw** [comment]
In example app there is no colors for events. Only for calendars. Did you wanted to get calendar color?

**Comment by thomassth** [comment]
You mean setting / getting each event color independent of the calendar color? 

Not sure if it's implemented, but jic this is the related Android API for reference 

[https://developers.google.com/calendar/v3/reference/colors](https://developers.google.com/calendar/v3/reference/colors)

**Comment by thomassth** [comment]
I think this is a function not yet implemented. 

But as of now there isn't much demand, and I can't seem to find corresponding API in iOS. You're welcome to contribute though.
