### ISSUE TITLE
Event is missing location parameter

### ISSUE THREAD

**Issue by RuneAlexanderLarsen** [builttoroam/device_calendar#266]
Is there a reason why the String parameter `location` is excluded from Event in this package?

>   /// The location of this event
>   String location;
> 
>   Event(this.calendarId,
>       {this.eventId,
>       this.title,
>       this.start,
>       this.end,
>       this.description,
>       this.attendees,
>       this.recurrenceRule,
>       this.allDay = false});

**Comment by matejdro** [comment]
Location is there, it is just missing in constructor. You can manually set it after constructing the event.

**Comment by diogosequeira94** [comment]
Can you consider adding it to the constructor as well as the other properties mentioned in the To/FromJson methods? Thanks
