### ISSUE TITLE
Event creation

### ISSUE THREAD

**Issue by rgluzman** [builttoroam/device_calendar#267]
Hello

I can't create events inIOS simulator with different calendars(calendars and events retrieving works), error code
PlatformException(404, The event with the ID  could not be found, null, null)
 
And it works Android with same code

Something particular in IOS

Regards

**Comment by codesxt** [comment]
Same error here.

**Comment by codesxt** [comment]
@rgluzman I found out that my problem was the same mentioned in https://github.com/builttoroam/device_calendar/issues/121. I was manually assigning eventId which seems to be a read-only variable. Without assigning that variable, it saved the event perfectly.

**Comment by andzejsw** [comment]
@rgluzman did @codesxt answer helped you?
