### ISSUE TITLE
Example app: Setting a recurrence end, then setting the recurrence end to be indefinitely will incorrectly save the event

### ISSUE THREAD

**Issue by stephensamonte** [builttoroam/device_calendar#268]
When editing or creating a calendar event, if you set recurring to end (specified time or after a number of occurances):

<img width="336" alt="Screen Shot 2020-10-25 at 3 15 20 AM" src="https://user-images.githubusercontent.com/30998408/97101060-69ac9b80-1670-11eb-9e6e-5ff90d4b131e.png">

Save the event by clicking the `checkmark floating action button`.

Open the same event again and set the recurrence end to be indefinitely.

<img width="336" alt="Screen Shot 2020-10-25 at 3 16 38 AM" src="https://user-images.githubusercontent.com/30998408/97101072-8a74f100-1670-11eb-8d50-1199bfa77af3.png">

Save the event by clicking the `checkmark floating action button`.

The event end will not be set to indefinitely:

<img width="335" alt="Screen Shot 2020-10-25 at 3 18 56 AM" src="https://user-images.githubusercontent.com/30998408/97101114-e50e4d00-1670-11eb-972e-4e36f356830b.png">

Here, in the calendar view, I only see only one event was created rather than multiple events since it should end indefinitely (there should be several events shown). 

This was the recurring event value saved: 

```
I/flutter (10340): RECURRING: {totalOccurrences: 1, interval: 1, recurrenceFrequency: 0}
```

This is the intended recurranceRule for an indefinite event: 
```
I/flutter (10340): RECURRING: {interval: 1, recurrenceFrequency: 0}
```

**Comment by andzejsw** [comment]
I am not able to replicate this issue following these steps. Could it be, that this issue is fixed!? Can you take a look and check if issue still remains?

**Comment by stephensamonte** [comment]
@andzejsw This is still an issue in the https://github.com/builttoroam/device_calendar develop branch. I updated the original issue comment to include clicking save as a step.
