### ISSUE TITLE
Event start and end datetime, having issues with gmt time zone

### ISSUE THREAD

**Issue by juampiq6** [builttoroam/device_calendar#274]
Hi, nice library by the way.
Im having an issue where i specify an exact DateTime for the start and the ending of the event, when i create the event using the "createOrUpdateEvent".
On android, the dates are not transformed (not applied the time zone, -3 in my case).
On iOS, the dates are transformed ( my timezone is applied, so if I specify for example, today at 15:00, the event dates are transformed according to my time zone, -3, resulting on 12:00).

**Comment by andzejsw** [comment]
Should close this after PR https://github.com/builttoroam/device_calendar/pull/297 is published.

**Comment by mzl1988** [comment]
device_calendar: ^4.0.1-dev.13167 
The same problem still occurs after the time zone has been set
```
Future<void> configureLocalTimeZone() async {
    tz.initializeTimeZones();
    final String? timeZoneName = await FlutterNativeTimezone.getLocalTimezone();
    print(timeZoneName);
    tz.setLocalLocation(tz.getLocation(timeZoneName!));
  }
```
