### ISSUE TITLE
Allow auth and app crash.

### ISSUE THREAD

**Issue by XiaoJianXiaoXu** [builttoroam/device_calendar#277]
First, Refuse calendar authorization. Then to request permission, a alert will pop up and select Allow.  

In android (vivo), app Crash.
In iOS, **requestPermissions** is false.

**Comment by onlycyndi** [comment]
I had a problem when I refuse calendar authorization like you, and it crashed many times when I restart the app. I try to reset it     
 in the Simulator -> Device -> Erase All Content and Setting , and rebuild the iOS file . it doesn't work until I add the permission below.  - -#
<key>NSCalendarsUsageDescription</key>
<string>INSERT_REASON_HERE</string>

**Comment by andzejsw** [comment]
Does this error still exists on latest dev? Did @onlycyndi answer helped?
