### ISSUE TITLE
Project state?

### ISSUE THREAD

**Issue by nicolashaan** [builttoroam/device_calendar#279]
Hi @nickrandolph,

What's the status of this project? Is it still maintained? Can I expect new releases with current PRs?

Best regards,
Nicolas

**Comment by nickrandolph** [comment]
HI @nicolashaan apologies for being absent
I'll endeavour to go through the PRs this week and get a new release out

**Comment by nickrandolph** [comment]
I've merged a couple of PRs and there should be a new pre-release build being built and pushed out. Feel free to give it a test and report back any issues
