### ISSUE TITLE
Module 'device_calendar' not found when Release iOS for Distribution

### ISSUE THREAD

**Issue by natheemy** [builttoroam/device_calendar#280]
When i try to distribution my app following step from https://flutter.dev/docs/deployment/ios, i got error Module 'device_calendar' not found on step 'Select Product > Archive to produce a build archive.
![Screenshot 2021-03-01 at 12 49 38 PM](https://user-images.githubusercontent.com/24647931/109464653-00f58580-7a8d-11eb-8c4e-42c18244d62a.png)

**Comment by saschaernst** [comment]
That solved it for me:
https://github.com/flutter/flutter/issues/43986#issuecomment-612615174

**Comment by andzejsw** [comment]
@natheemy did @saschaernst  comment fixed your issue?
