### ISSUE TITLE
Not seeing outlook calendar, gmail is fine.

### ISSUE THREAD

**Issue by IntuitiveDeveloper** [builttoroam/device_calendar#282]
I am trying the device calendar on Android AVD. On the VD, I have both gmail and outlook accounts created. The calendar list includes the gmail calendar, but not the outlook. Does anybody know what may be an issue ?

I/flutter ( 8547): Holidays in United States
I/flutter ( 8547): Birthdays
I/flutter ( 8547): vkxxxx@gmail.com

**Comment by andzejsw** [comment]
Have you tried to sync Outlook calendar with Android calendar on device?
