### ISSUE TITLE
Null-Safety Migration

### ISSUE THREAD

**Issue by GoldenSoju** [builttoroam/device_calendar#283]
I haven't found any entry about it yet, so I was wondering if the package will be migrated to null-safety (soon) ?

**Comment by andzejsw** [comment]
I have created pull request implementing null safety logic: https://github.com/builttoroam/device_calendar/pull/286
Hope soon it will be implemented and if needed, improved.

**Comment by thomassth** [comment]
> I have created pull request implementing null safety logic: #286
> Hope soon it will be implemented and if needed, improved.

On my I did the same thing
#287

Can we combine our work in some way

**Comment by GoldenSoju** [comment]
i haven't seen any activity from the package owner(s) for a while now...can we assume this package was abandoned?

**Comment by andzejsw** [comment]
> i haven't seen any activity from the package owner(s) for a while now...can we assume this package was abandoned?

I think that it is safe to say that. Some very needed PR aren't touched for quite some time.

**Comment by thomassth** [comment]
I don't mind splitting and republish the package to pub.dev, at least it's more convenient. 
But I don't have much experience in coding, I can take pull requests but probably can't contribute much.

**Comment by nickrandolph** [comment]
Hey all, again apologies, I've had other work commitments. If you guys are interested I can add you as maintainers as happy to take contributors.

**Comment by andzejsw** [comment]
> Hey all, again apologies, I've had other work commitments. If you guys are interested I can add you as maintainers as happy to take contributors.
> Just as FYI the build and publish is pretty much automated, so it's just a matter of raising PRs to the appropriate branch. If you're interested, I'd be happy to help you guys contribute

In my opinnion @thomassth  PR now is better than mine.  But yeah, i would be happy to be a maintainer, if you need any help. Probably @thomassth has no problem with that too.

**Comment by nickrandolph** [comment]
@thomassth and @andzejsw I've sent you invites to the Other team at Built to Roam. Let me know if you have any issues accepting the invites

**Comment by andzejsw** [comment]
> @thomassth and @andzejsw I've sent you invites to the Other team at Built to Roam. Let me know if you have any issues accepting the invites

Hi. I don't see any invite.

**Comment by nickrandolph** [comment]
Do you have a different email account associated with your github account?

**Comment by thomassth** [comment]
I got the invite when I visit [https://github.com/builttoroam](https://github.com/builttoroam)

**Comment by andzejsw** [comment]
Merged PR https://github.com/builttoroam/device_calendar/pull/287 into develop branch.
