### ISSUE TITLE
Difference end date between iOS and Android (allday event)

### ISSUE THREAD

**Issue by maerlynflagg** [builttoroam/device_calendar#293]
hello!

current Version:

`device_calendar: ^3.1.0`

if i entering a all day event, for example 2021-04-21 on iOS and Android calendar (CEST time zone), there is a different result retrieving the events.

**iOS (this is correctly)**

start: 2021-04-21 00:00
end: 2021-04-21 23:59

it is one allday event.

**Android**

start: 2021-04-20 02:00
end: 2021-04-**21** 02:00

looks like 2 all day event.

so, i have the detect, if the current device an Android or iOS device.  
is this pattern always on Android? 

but is there a way to give always the same result for both?

**Comment by Edirisinghe** [comment]
I have the same issue

**Comment by nickrandolph** [comment]
@andzejsw can we check to see whether this has been fixed with the updated implementation for timezones? I think it might have been because it was one of the issues I was aware of when I was making those changes.

**Comment by andzejsw** [comment]
@nickrandolph Currently it looks like that Android part works now  on latest PR. Today i will take a look on iOS and hopefully we will be able to merge PR at least in dev branch.

**Comment by henry2man** [comment]
Just in case anyone (like me) needs to patch this using older versions, here it is a sample code that fixes event dates on Android.

```dart
Event event = .... // here is your event retrieve code

// Workaround allDay events. on Android.  https://github.com/builttoroam/device_calendar/issues/293
if (Platform.isAndroid && event.allDay) {
   DateTime start = event.start;
   DateTime end = event.end;
   var millisecondsOffset = (start.hour * 60 + start.minute) * 60 * 1000;
   // 00:00
   event.start = start.add(Duration(milliseconds: -millisecondsOffset));
   // 23:59
   event.end = end.add(Duration(milliseconds: -millisecondsOffset - 1));
}

// At this point, "event" have correct hours & minutes

```

PS: @maerlynflagg Is this similar to your approach?

**Comment by Edirisinghe** [comment]
As a workaround, I did the same thing as this.

**Comment by maerlynflagg** [comment]
> @nickrandolph Currently it looks like that Android part works now on latest PR. Today i will take a look on iOS and hopefully we will be able to merge PR at least in dev branch.

for your information:

i'm not sure, which PR you mean. so if the merge done, so the difference between iOS and Android still exists in 

`device_calendar: ^4.0.1-dev.13167`.

iOS is still fine. Android looks the result event like this:

```
hashCode:-747250448
url:null
title:"TEST"
start:TZDateTime (2021-06-17 00:00:00.000Z)
reminders:List (0 items)
recurrenceRule:null
location:null
eventId:"175"
end:TZDateTime (2021-06-18 00:00:00.000Z)
description:null
calendarId:"1"
availability:Availability (Availability.Free)
attendees:List (0 items)
allDay:true
```

so currently , i'm still using a workaround for Android.

**Comment by phamquoctrongnta** [comment]
@maerlynflagg Which solution for this issue?

**Comment by phamquoctrongnta** [comment]
@henry2man @andzejsw @maerlynflagg Which solution for this issue?
