### ISSUE TITLE
device_calendar.dart error

### ISSUE THREAD

**Issue by geokos009** [builttoroam/device_calendar#301]
Hi,

I was checking the example flutter app and this is the error (pasted below) that cropped up after I did a flutter upgrade to 2.12.3. I did a flutter downgrade and this error continues. Could you help with this?

Thanks.

George.

Launching lib/main.dart on CPH1819 in debug mode...
Running Gradle task 'assembleDebug'...
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/device_calendar-3.1.0/lib/src/device_calendar.dart:301:28: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.12 or higher.
        Function(Result<T>)? assertParameters,
                           ^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/device_calendar-3.1.0/lib/src/device_calendar.dart:302:27: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.12 or higher.
        Map<String, Object?> Function()? arguments,
                          ^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/device_calendar-3.1.0/lib/src/device_calendar.dart:302:40: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.12 or higher.
        Map<String, Object?> Function()? arguments,
                                       ^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/device_calendar-3.1.0/lib/src/device_calendar.dart:303:28: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.12 or higher.
        T Function(dynamic)? evaluateResponse,
                           ^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/device_calendar-3.1.0/lib/src/device_calendar.dart:286:7: Error: The getter 'ChannelConstants' isn't defined for the class 'DeviceCalendarPlugin'.
 - 'DeviceCalendarPlugin' is from 'package:device_calendar/src/device_calendar.dart' ('../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/device_calendar-3.1.0/lib/src/device_calendar.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'ChannelConstants'.
      ChannelConstants.methodNameDeleteCalendar,
      ^^^^^^^^^^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/device_calendar-3.1.0/lib/src/device_calendar.dart:288:9: Error: The method '_validateCalendarIdParameter' isn't defined for the class 'DeviceCalendarPlugin'.
 - 'DeviceCalendarPlugin' is from 'package:device_calendar/src/device_calendar.dart' ('../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/device_calendar-3.1.0/lib/src/device_calendar.dart').
Try correcting the name to the name of an existing method, or defining a method named '_validateCalendarIdParameter'.
        _validateCalendarIdParameter(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/device_calendar-3.1.0/lib/src/device_calendar.dart:294:9: Error: The getter 'ChannelConstants' isn't defined for the class 'DeviceCalendarPlugin'.
 - 'DeviceCalendarPlugin' is from 'package:device_calendar/src/device_calendar.dart' ('../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/device_calendar-3.1.0/lib/src/device_calendar.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'ChannelConstants'.
        ChannelConstants.parameterNameCalendarId: calendarId,
        ^^^^^^^^^^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/device_calendar-3.1.0/lib/src/device_calendar.dart:326:63: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.12 or higher.
      _parsePlatformExceptionAndUpdateResult<T>(e as Exception?, result);
                                                              ^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/device_calendar-3.1.0/lib/src/device_calendar.dart:310:20: Error: The getter 'hasErrors' isn't defined for the class 'Result<T>'.
 - 'Result' is from 'package:device_calendar/src/models/result.dart' ('../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/device_calendar-3.1.0/lib/src/models/result.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'hasErrors'.
        if (result.hasErrors) {
                   ^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script '/Users/georgekoshy/Developer/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 991

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/georgekoshy/Developer/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 25s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by thomassth** [comment]
Please consider using v4 in prerelease, which supports null safety (especially in flutter releases 2.12 or above).

**Comment by geokos009** [comment]
Thank you so much for the prompt response.

It works with the pre-release V4.
