### ISSUE TITLE
[App in Background] MissingPluginException(No implementation found for method hasPermissions on channel plugins.builttoroam.com/device_calendar)

### ISSUE THREAD

**Issue by loicgeek** [builttoroam/device_calendar#303]
I have to  add events to calendar when the app is in background. When I tried, I got this error? please how to register this plugin to work in background ? 
I have seen something similar here: https://pub.dev/packages/flutter_downloader

**Comment by andzejsw** [comment]
Are you using 3.1 version or 4.x Prerelease?
And how are you running this specific method for event inserting!? Do you have some foreground service or are you using some push service for event inserting?
Flutter for running code on background uses isolates. Take a look here: https://medium.com/flutter/executing-dart-in-the-background-with-flutter-plugins-and-geofencing-2b3e40a1a124
As far as I know, there is no logic in this plugin for background process handling. But in closest week I will take a look and check this. But feel free to contribute your code through PR, if you find how can it be done sooner.

**Comment by loicgeek** [comment]
@andzejsw  others plugins are working like https://pub.dev/packages/flutter_secure_storage and firebase plugins.Normally I just have to manually register the plugin, but it seems like the implementation of the plugin doesnt allow it.

**Comment by loicgeek** [comment]
I am using the version 3.2.0 in develop-branch

**Comment by loicgeek** [comment]
@andzejsw  ```
  D/Ringtone(17876): Successfully created local player
I/flutter (17876): Got an appointment
I/flutter (17876): 60a6625b63ccbb493bac6a70
I/flutter (17876): MissingPluginException(No implementation found for method retrieveCalendars on channel plugins.builttoroam.com/device_calendar)
I/flutter (17876): NoSuchMethodError: The method 'firstWhere' was called on null.
I/flutter (17876): Receiver: null
I/flutter (17876): Tried calling: firstWhere(Closure: (Calendar) => bool, orElse: Closure: () => Null)
E/flutter (17876): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The getter 'id' was called on null.
E/flutter (17876): Receiver: null
E/flutter (17876): Tried calling: id
E/flutter (17876): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter (17876): #1      AppointmentModel.addToCalendar
package:chairwatch_flutter/models/appointment_model.dart:572
E/flutter (17876): <asynchronous suspension>
E/flutter (17876): #2      _onBackgroundMessage
package:chairwatch_flutter/main.dart:69
E/flutter (17876): <asynchronous suspension>
E/flutter (17876): #3      _firebaseMessagingCallbackDispatcher.<anonymous closure>
package:firebase_messaging_platform_interface/…/method_channel/method_channel_messaging.dart:52
E/flutter (17876): #4      MethodChannel._handleAsMethodCall
package:flutter/…/services/platform_channel.dart:430
E/flutter (17876): #5      MethodChannel.setMethodCallHandler.<anonymous closure>
package:flutter/…/services/platform_channel.dart:383
E/flutter (17876): #6      _DefaultBinaryMessenger.handlePlatformMessage
package:flutter/…/services/binding.dart:283
E/flutter (17876): #7      _invoke3.<anonymous closure> (dart:ui/hooks.dart:280:15)
E/flutter (17876): #8      _rootRun (dart:async/zone.dart:1190:13)
E/flutter (17876): #9      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (17876): #10     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
D/FLTFireMsgReceiver(17876): broadcast received for message
D/FlutterSecureStoragePl(17876): Initializing StorageCipher
D/FlutterSecureStoragePl(17876): StorageCipher initialization complete
E/flutter (17876): #11     _invoke3 (dart:ui/hooks.dart:279:10)
E/flutter (17876): #12     _dispatchPlatformMessage (dart:ui/hooks.dart:154:5)
E/flutter (17876):

```

**Comment by loicgeek** [comment]
@andzejsw  hello, I just want you to know that I end up updating flutter to 2.2 , without migrating my project to null safety, and it is working fine, thank you for the support.
