### ISSUE TITLE
TZDateTime migration guide

### ISSUE THREAD

**Issue by thomassth** [builttoroam/device_calendar#308]
When migrating to latest dev release, `Event` classes now requires `TZDateTime` instead of `DateTime`.

`TZDateTime` seems to come from the [Timezone](https://pub.dev/packages/timezone) package.

Should the docs be updated to include this, or can the `TZDateTime` class be exposed from within the package?

**Comment by andzejsw** [comment]
I think, that we should update docs for those, who use Event classes. Exposing  `TZDateTime` class in my opinion would be wrong, cause it comes from different package.

**Comment by zakton5** [comment]
What if we don't know or care about the time and just care about the users local time? I have no need for the timezone package and now I am forced to use it. Is using the timezone dependency absolutely necessary?

**Comment by tverra** [comment]
I certainly don't need this in my app, since no other widghet that I know of uses TZDateTime. And now I'm here looking for documentation on how to convert my DateTimes into TZDateTimes without messing up the dates.

**Comment by henry8th** [comment]
Also when using await FlutterNativeTimezone.getLocalTimezone() as used in the docs crashes my app, i think due to the dependency version not being the latest (1.5.0) as opposed to (2.0.0)

**Comment by phamquoctrongnta** [comment]
Any update?
