### ISSUE TITLE
UTC TZDateTime

### ISSUE THREAD

**Issue by albatrosify** [builttoroam/device_calendar#309]
How can I create a TZDateTime that is UTC, but compatible with this Plugin?
As soon as I create a TZDateTime that is UTC (Etc/UTC) but not fits the Country/City schema, I get an error, as Etc/UTC is not part of the location list of this plugin

TZDateTime is created like this:
`TZDateTime start = TZDateTime.utc(_start.year, _start.month, _start.day, _start.hour, _start.minute);`

Plugin-Code has an Exception @ 203 lib/src/device_calendar.dart
![image](https://user-images.githubusercontent.com/64252708/121309522-90b79500-c902-11eb-84b5-6d214f843954.png)

**Comment by thomassth** [comment]
`TZDateTime` is handled by another package, see [here](https://pub.dev/packages/timezone)

Apparently `etc/UTC` is not in the default database, and you need to choose the full database with `initializeTimeZone('packages/timezone/data/latest_all.tzf')`

**Comment by nsendhavdq** [comment]
How we can change DateTime to TZDateTime , because before this update we are taking DateTime as input. Thanks in advance.

**Comment by LanceOwide** [comment]
@nsendhavdq 
see : https://pub.dev/packages/timezone
