### ISSUE TITLE
Event.fromJson() always returns DateTime.Now() for Event.start.

### ISSUE THREAD

**Issue by severin13** [builttoroam/device_calendar#315]
Dear all,
I am saving an Event as String to a local SQFlite Database using toJson which works fine, the String stored is:

{"calendarId":"15","eventId":"578","eventTitle":"Coop","eventDescription":null,"eventStartDate":1625812200000,"eventStartTimeZone":"UTC","eventEndDate":1625812200000,"eventEndTimeZone":"UTC","eventAllDay":false,"eventLocation":null,"eventURL":null,"availability":"FREE","reminders":[{"minutes":0}]}

However, when I try to recreate an Event from Json, I always get the current time as eventStartDate.  I checked Event.fromJson and found:
**final int? startTimestamp = json['start'];**
  final String? startLocationName = json['startTimeZone'];
  var startTimeZone = timeZoneDatabase.locations[startLocationName];
  startTimeZone ??= local;
  **start = startTimestamp != null
      ? TZDateTime.fromMillisecondsSinceEpoch(startTimeZone, startTimestamp)
      : TZDateTime.now(local);**

As my event in json-format has no 'start' key, startTimeStamp == null and I get TZDateTime.now(local) all the time. Is this a mistake or am I missing something here?

Thanks very much for looking at this and all your efforts with this package!
Severin

**Comment by andzejsw** [comment]
Looks like mistake. Can you make PR with fix?

**Comment by severin13** [comment]
That would be my first PR ever ;-) I will give it a shot...

**Comment by CJohnson19** [comment]
It seems this bug also happens for end time, title, location, url, etc.

@severin13 are you still planning on making a PR for this? I wouldn't want to step on your toes by submitting one myself.

**Comment by severin13** [comment]
@CJohnson19 I already subimtted a PR, but according to your findings, that would only be a partial fix. So sure, feel free to submit an additional PR, you won't step on my toes ;-)

**Comment by CJohnson19** [comment]
Sounds good! I can't believe I missed your PR. I think it would be better organizationally for me to start a new issue for the remaining parts since your fix is already there.
