### ISSUE TITLE
Json methods use different attributes

### ISSUE THREAD

**Issue by CJohnson19** [builttoroam/device_calendar#320]
The `event` model uses attribute names with a different name in `toJson` and `fromJson`. #316 covers the start and end time fields, but `title`, `description`, `allDay`, and `url` also have this issue.

Example:

```dart
Map<String, dynamic> toJson() {
  ...
  data['eventTitle'] = title;
  data['eventDescription'] = description;
```

```dart
Event.fromJson(Map<String, dynamic>? json) {
    ...
    title = json['title'];
    description = json['description'];
```

There is currently a unit test for some of these fields in `Event_Serialises_Correctly`, which fails.

I'd be happy to submit a PR to fix the attribute changes.

I would also suggest having the CI run the `FlutterTest@0` task as a check - and can include that in the same PR if the owners agree it should be included.

**Comment by thomassth** [comment]
We really need more work in test and documentation area, so feel free to make a PR.

**Comment by thomassth** [comment]
#382 should fix any JSONs created after this PR.

Some kind of convertor may be needed for previously created JSONs.

**Comment by thomassth** [comment]
Things should be fixed now. Reopen this if it isn't.
