### ISSUE TITLE
Flutter build process reports device_calendar uses a deprecated version of the Android embedding

### ISSUE THREAD

**Issue by mikeryder** [builttoroam/device_calendar#326]
I upgraded to 4.0.1 of device_calendar (for null-safety).  I was surprised the warning message of deprecated version of the Android embedding still comes up during build.  I am doing something wrong or is this expected behavior?

**Comment by koenniem** [comment]
I agree. To avoid unexpected runtime failures, or future build failures, this plugin must be upgraded to Android embedding V2. Otherwise, a future release of Flutter will remove these deprecated APIs.

https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration

**Comment by thomassth** [comment]
Depend on the underlying issue, this can be a simple update to dependencies and not change anything, to waiting for others to update their package / find a new one.

Feel free to try and submit a PR if it works.
