### ISSUE TITLE
Android: After permission got rejected "requestPermissions()" does not ask again

### ISSUE THREAD

**Issue by hartmannj** [builttoroam/device_calendar#332]
I am not sure if this is intended behaviour but I think for the developer it would be more flexible if requestPermissions() always opens the Android permission dialog even if the user had the permission previously rejected.
Otherwise we have to display a separate dialog explaining the user to go to the Android permission settings and change it there. This would not be a very intuitive user experience.

**Comment by thomassth** [comment]
If you do a "hard reject" you need to go to the app info page to change permissions.

If you choose "allow once" for camera or mic, the pop-up should come up again next time. This is not available for calendars. 

We can link to said page but other than that we can't do much. It's a system wide policy.

**Comment by sowens-csd** [comment]
I believe this issue is closed. Please reopen or open a new issue if you still have questions.
