### ISSUE TITLE
CI/CD upgrade

### ISSUE THREAD

**Issue by thomassth** [builttoroam/device_calendar#346]
Related to #344

Somehow the latest dependency upgrade is not working here. It seems that the flutter used within the server was and old version. 

We may need to upgrade the current azure pipeline, or maybe switch to github action?

**Comment by sowens-csd** [comment]
Who has access to update the Azure pipeline? Is the pipeline configuration committed with this project? I had a quick look and didn't see it.

**Comment by sowens-csd** [comment]
I'm just catching up to where you were @thomassth, looks like the Azure pipeline is using Flutter 2.2.1. I'll have another look at the Azure pipeline configuration. 

I'd vote for switching to GitHub actions since I'm more familiar with those and I think it would allow all committers better access to the build tooling. I'm assuming that Azure picks up the latest version of the build configuration from the repo but I'm not certain of that. Have you made changes to the Azure build previously?

**Comment by sowens-csd** [comment]
So this issue https://stackoverflow.com/questions/69334583/azure-devops-ci-cd-not-installing-latest-flutter-version suggests that the FlutterInstall task being used is not being maintained anymore. They're suggesting using this one instead https://marketplace.visualstudio.com/items?itemName=hey24sheep.flutter looking for how to do that now.

**Comment by nickrandolph** [comment]
Hi all, I'll try to take a look at this during the week to get the build up and running agin.

**Comment by thomassth** [comment]
I've been playing with github actions on my side

It seems easy enough

**Comment by sowens-csd** [comment]
@thomassth I was going to ask if you'd seen any good news on the Azure build infrastructure but from the look of the commit verification on your recent merge it looks like the answer is no. I was wondering if we should use the work you've put into #347 and close this issue by having commits verified by Actions even if we don't have the full CI/CD stack working yet. Then we could merge #347 and other issues with passing verifications. Then create a new issue to finish off the CI/CD work. 

Thoughts?

**Comment by thomassth** [comment]
I'm working on making dev release automatic but otherwise things are ready to test

Because of how credentials are made, I think we can only test on prod to see if we can publish the package this way.

**Comment by sowens-csd** [comment]
Sounds like great progress, let me know if I can do anything to help. I agree that prod is likely the only way to test publishing.

**Comment by thomassth** [comment]
Ready to test on prod now :)

**Comment by thomassth** [comment]
We should keep this open until we have finished the migration.

**Comment by thomassth** [comment]
I think the keys are currently stored within Azure DevOps' system, not pulled from the build.

Either we
- port the secrets to Github, which only @nickrandolph has access to do
- Update the pipeline

**Comment by nickrandolph** [comment]
Hey sorry last week has been hectic. I will try to get the Azure build sorted asap.

**Comment by sowens-csd** [comment]
Thanks @nickrandolph.  If you put the secrets into GitHub then we could switch to Actions and wouldn't have to bother you for any future upgrades / changes.

**Comment by thomassth** [comment]
I also prefer Github Action, I think it's easier to maintain and reliable enough for our use. 

Pipeline seems more complex than Action, but we don't actually need all that complexity in our CI/CD.

**Comment by thomassth** [comment]
> I also prefer Github Action, I think it's easier to maintain and reliable enough for our use. 
> 
> Pipeline seems more complex than Action, but we don't actually need all that complexity in our CI/CD.

Also we can manually trigger a release on the web, in any branches we want, which can be very useful.

**Comment by thomassth** [comment]
@nickrandolph if you're busy, you can just dump the whole `CREDENTIAL.JSON` as a secret.

[Our workflow](https://github.com/sakebook/actions-flutter-pub-publisher) supports that too

**Comment by nickrandolph** [comment]
@thomassth the current pipeline supports a staged release process, so I don't seem much reason to move away from it. I get that I've been a bottleneck on this, so would be keen to discuss options for someone to help out when there are pipeline issues - I'd be able to give them access to the azure pipeline.

**Comment by thomassth** [comment]
If it's possible to share pipeline access then it's an advantage for us, since we can't read or write secrets on github as maintainer.

**Comment by sowens-csd** [comment]
@thomassth did you get pipeline access?
