### ISSUE TITLE
Version semantics

### ISSUE THREAD

**Issue by thomassth** [builttoroam/device_calendar#356]
We are a few buttons away from v4, but actually we have 2 to be pushed according to `changelog.md`

We have
A.
 [4.0.0-dev.12864](https://github.com/builttoroam/device_calendar/releases/tag/4.0.0-dev.12864), which is null safe with a few bug fixes
B. 
dev branch (not on pre-release) using new TZ blocks, among other internal upgrades

I feel that using TZ is a big change, and should be a more significant number bump. Also a null-safe version without TZ support might be favorable for people transitioning to null safety.

Which can be
- A=v4 and B=v4.1
The original plan that v4=null. 
- A=v3.9 and B=v4.0
 People who have `^3.x.x` in their files won't be auto-upgraded to v4, which needs some tinkering to run. But they will get v3.9 that is null safe. 
However people using `^4.0.1-dev` won't get anything until we have v4.0.1 on release. Since we still have a few PRs in the queue I think this can be done soon.

In each case, we can open a temp branch and PR to release.

Depends on #346

**Comment by sowens-csd** [comment]
I'd vote for v4 and v4.1. The null save upgrade to a code base is hard enough, as is testing it. Adding the TZ changes to it will make validating the change harder.

**Comment by thomassth** [comment]
> I'd vote for v4 and v4.1. The null save upgrade to a code base is hard enough, as is testing it. Adding the TZ changes to it will make validating the change harder. 

This is why I have the idea for `3.9`.

If you have `^3.2`, you will be getting `3.9`, with TZ changes. (ie. 4.0.0-12864 = 3.9)

Then, you may opt to upgrade to `^4.0`, with TZ changes etc

**Comment by sowens-csd** [comment]
Your logic makes sense and I'm happy to go whichever way you prefer. 

My thinking, in case it helps, is that the null safety changes are major breaking changes and probably deserving of the 4.x update. I go for more version upgrades rather than less so if the TZ changes are big enough I'd even support 4.x and 5.x, but I know that's not a universal preference.

**Comment by thomassth** [comment]
That's a valid point.

I'm rather confident that null safety doesn't do harm because it seems quite stable and pain-free to me and others here when migrating. Most issues here are either for new features or already present before null safety. 

Let me know if there's some probable issues though, v4 would be more suitable if that's the case.

(v4 and v5 feels kinda too much so I didn't add that in)

**Comment by sowens-csd** [comment]
As long as there's a version of the plugin that has only the null safety changes then I think it's fine. I'm not so concerned about issues with as I am with having to test both a null safe app migration against a plugin with both null safety changes and other. Both of your proposals pass that test so either is fine.

**Comment by sowens-csd** [comment]
I think we can close this now? And huge congrats on the release @thomassth, great work!
