### ISSUE TITLE
Problems with flutter publish

### ISSUE THREAD

**Issue by thomassth** [builttoroam/device_calendar#362]
Part of #346

Appearantly our publish credentials are expired since March. That's why our action stuck in a loop. 

Also see
https://github.com/sakebook/actions-flutter-pub-publisher/issues/22

I think @nickrandolph need to get a new one from pub.dev

**Comment by sowens-csd** [comment]
Thanks @thomassth, I pinged @nickrandolph. He said he'll be online tomorrow morning, hopefully he can resolve then.

**Comment by sowens-csd** [comment]
so @nickrandolph got some new credentials and I tried a build but it still appeared to hang.

**Comment by thomassth** [comment]
It seems that Google needs another layer of auth to proceed. I thought credentials would be enough 😒

Someone need to click the generated link to give auth to GHA access to publish. Probably @nickrandolph 's account for pub.dev

**Comment by sowens-csd** [comment]
Okay, I've pinged Nick.

**Comment by nickrandolph** [comment]
Hi guys. Where do I find the link I need to click through on?

**Comment by thomassth** [comment]
https://github.com/builttoroam/device_calendar/runs/4323788024?check_suite_focus=true

Try the link in the logs

**Comment by thomassth** [comment]
After some more digging apparently we also need to be verified too.

https://github.com/k-paxian/dart-package-publisher/issues/14

(And they've just resolved this less than a month ago. If we did this any sooner we will be totally stuck.)

**Comment by sowens-csd** [comment]
I think the publisher is verified on pub.dev. That means it should work?

**Comment by sowens-csd** [comment]
I killed that task you started @thomassth it had been going for hours. Thoughts?

**Comment by thomassth** [comment]
Forgot to add back the `--force` arg

It asks for confirmation without it.

You can do the edit if you have the time

**Comment by sowens-csd** [comment]
That looks like success @thomassth! I see the new version on pub.dev.

**Comment by thomassth** [comment]
Interestingly `d` goes before numbers

But that's another problem so I'm closing this now!
