### ISSUE TITLE
Deprecated API

### ISSUE THREAD

**Issue by severin13** [builttoroam/device_calendar#376]
Hi,
Since the latest Flutter update I receive this warning during build with either version 4.00 and 4.0.1-dev.13167. Is there any way to fix this on my side? I tried to dive into native code but unfortunately my Kotlin-knowledge is not sufficient.
Thanks in advance for any help with this!

The plugin `device_calendar` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing itsince a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by thomassth** [comment]
I’ve build it a number of times and it should be fixed at v4.

Try removing it in `pubspec`, run `pub get`, then add the package back. It usually flushes all old parts and get you the latest one.

**Comment by severin13** [comment]
Thanks very much for the hint. If anyone is facing the same problem, I could finally fix the issue by:
1. Remove device_calendar entry from pubspec.yaml
2. flutter clean
3. flutter pub cache repair (Warning: this might take a while depending on how many packages you are using)
4. add device_calendar 4.0.0 back to pubspec.yaml
5. flutter pub get

**Comment by thomassth** [comment]
Personally I would skip step 3 because it downloads a whole lot more than you need, and you will do `pub get` anyway. Glad to help though!

**Comment by severin13** [comment]
Somehow it did not work for me without step 3, but yes, if it is working without it the better.

**Comment by wanpaya** [comment]
Hi,

This plugin is great work. By the way, is that possible to upgrade timezone dependencies lib of device_calendar to ^0.9.0 instead of ^0.8.0?
I've found that flutter_local_notifications required minimum of timezone lib at 0.9.0. Since then I can not upgrade device_calendar to ^4.0.0 or greater.

**Comment by IVLIVS-III** [comment]
Hi @wanpaya, it's already in the works. A patch has already been merged (see https://github.com/builttoroam/device_calendar/pull/440).

Just no new version has been pushed yet.
I'm not quite shure what keeps us from pushing a new version to pub.dev.
If it's urgent, you could directly depend on the `develop` branch. However, this branch might not be fully tested yet.
