### ISSUE TITLE
Unable to build release apk with Flutter 2.8.1/2.10.1

### ISSUE THREAD

**Issue by dmitry-kotorov** [builttoroam/device_calendar#411]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':device_calendar:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/Users/dima/.gradle/caches/transforms-3/f3d45056847818752b9a313ae43affe3/transformed/core-1.7.0/res/values/values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.

**Comment by thomassth** [comment]
Does clearing cache help?

Can't deduce much from your log

**Comment by thomassth** [comment]
Should be fixed with `4.2`
