### ISSUE TITLE
Permission cancel/ renew

### ISSUE THREAD

**Issue by JulianGerman** [builttoroam/device_calendar#415]
How can I switching permission / access to calendar for example by switching cupertino switch? I see that we can set the permission only once, after that there is no possibility to set it back to initial state.

**Comment by thomassth** [comment]
I presume you're on iOS right?

The app itself can't do anything once the user has denied permission. All you can do is point your user to iOS settings and ask them to change it there.

However you can detect if the permission is denied, and display a suitable dialog to your user.

**Comment by JulianGerman** [comment]
ok perfect thank you for fast response.
