### ISSUE TITLE
Documentation not sufficient

### ISSUE THREAD

**Issue by anushkachauhxn** [builttoroam/device_calendar#417]
### Current documentation is not helpful

[This](https://itnext.io/using-device-calendar-library-in-flutter-to-communicate-with-android-ios-calendar-95b2d8c77b40) is the only article I found that tries to explain it in steps but the code is outdated and doesn't work.

#### Please provide simpler examples with images/videos/gifs of the result. 

- Creating different use cases and describing them separately will be very helpful.
- *Example:* Click on this button to create an event in the device's local calendar with given date, time and title.

**Comment by thomassth** [comment]
See #422
