### ISSUE TITLE
[Dublicate Code] parseStringToAvailability called twice in Event.fromJson (Event Class - Dart)

### ISSUE THREAD

**Issue by GoldenSoju** [builttoroam/device_calendar#418]
Dublicate code I found in the Event class:

`availability = parseStringToAvailability(json['availability']);`

-> this is being called twice in lines 140 and 149 (Event.fromJson)

https://github.com/builttoroam/device_calendar/blob/988f671f43516d4f6d7ec4969172b7f4b84fa833/lib/src/models/event.dart#L140

https://github.com/builttoroam/device_calendar/blob/988f671f43516d4f6d7ec4969172b7f4b84fa833/lib/src/models/event.dart#L149

If I can file a PR I will soon hopefully, otherwise, leaving this here to not forget it.

**Comment by thomassth** [comment]
According to @catcecilia, seems to be fixed.
