### ISSUE TITLE
PlatformException(500, ownerAccount must not be null, null, null)

### ISSUE THREAD

**Issue by SungHyun22** [builttoroam/device_calendar#424]
I got this problem on Galaxy S9.
I tested with other phone and it's working. 
only my phone throw this exception.

*if you need more information about this problem just ask me*

**Comment by thomassth** [comment]
This is no information at all, I have nothing to work with

**Comment by SungHyun22** [comment]
I installed device_calendar-4.2.0 example app.
and I got this exception on the SM-G960N.
below is my flutter doctor -v info

[√] Flutter (Channel stable, 3.0.0, on Microsoft Windows [Version 10.0.19043.1645], locale ko-KR)
    • Flutter version 3.0.0 at C:\Users\LEE\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (11 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\LEE\AppData\Local\Android\Sdk
    • Platform android-Tiramisu, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\LEE\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.5.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.5.29926.136
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.4
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.67.2)
    • VS Code at C:\Users\LEE\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1645]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 101.0.1210.32

[√] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by SungHyun22** [comment]
below is the error code

I/flutter (23494): PlatformException(500, ownerAccount must not be null, null, null)
I/OpenGLRenderer(23494): doUpdatePositionAsync is called and callVoidMethod
E/flutter (23494): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: type 'Null' is not a subtype of type 'List<Calendar>' in type cast
E/flutter (23494): #0      _CalendarsPageState._retrieveCalendars.<anonymous closure>
package:device_calendar_example/…/pages/calendars.dart:138
E/flutter (23494): #1      State.setState
package:flutter/…/widgets/framework.dart:1109
E/flutter (23494): #2      _CalendarsPageState._retrieveCalendars
package:device_calendar_example/…/pages/calendars.dart:137
E/flutter (23494): <asynchronous suspension>
E/flutter (23494):

**Comment by SungHyun22** [comment]
@thomassth I'm sorry I didn't provide enough information in the first place. Could you please review this issue again with the above information?
