### ISSUE TITLE
PlatformException(500, ownerAccount must not be null, null, null)

### ISSUE THREAD

**Issue by SungHyun22** [builttoroam/device_calendar#427]
I installed device_calendar-4.2.0 example app.
and I got this exception on the SM-G960N.

## Flutter doctor

[√] Flutter (Channel stable, 3.0.0, on Microsoft Windows [Version 10.0.19043.1645], locale ko-KR)
• Flutter version 3.0.0 at C:\Users\LEE\flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision ee4e09cce0 (11 days ago), 2022-05-09 16:45:18 -0700
• Engine revision d1b9a6938a
• Dart version 2.17.0
• DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
• Android SDK at C:\Users\LEE\AppData\Local\Android\Sdk
• Platform android-Tiramisu, build-tools 30.0.3
• ANDROID_HOME = C:\Users\LEE\AppData\Local\Android\Sdk
• Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
• Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
• All Android licenses accepted.

[√] Chrome - develop for the web
• Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.5.2)
• Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
• Visual Studio Community 2019 version 16.5.29926.136
• Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 2021.2)
• Android Studio at C:\Program Files\Android\Android Studio
• Flutter plugin can be installed from:
https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] IntelliJ IDEA Community Edition (version 2019.3)
• IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.4
• Flutter plugin can be installed from:
https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.67.2)
• VS Code at C:\Users\LEE\AppData\Local\Programs\Microsoft VS Code
• Flutter extension version 3.40.0

[√] Connected device (3 available)
• Windows (desktop) • windows • windows-x64 • Microsoft Windows [Version 10.0.19043.1645]
• Chrome (web) • chrome • web-javascript • Google Chrome 101.0.4951.67
• Edge (web) • edge • web-javascript • Microsoft Edge 101.0.1210.32

[√] HTTP Host Availability
• All required HTTP hosts are available

## error log

I/flutter (23494): PlatformException(500, ownerAccount must not be null, null, null)
I/OpenGLRenderer(23494): doUpdatePositionAsync is called and callVoidMethod
E/flutter (23494): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: type 'Null' is not a subtype of type 'List' in type cast
E/flutter (23494): #0 _CalendarsPageState._retrieveCalendars.
package:device_calendar_example/…/pages/calendars.dart:138
E/flutter (23494): https://github.com/builttoroam/device_calendar/pull/1 State.setState
package:flutter/…/widgets/framework.dart:1109
E/flutter (23494): https://github.com/builttoroam/device_calendar/pull/2 _CalendarsPageState._retrieveCalendars
package:device_calendar_example/…/pages/calendars.dart:137
E/flutter (23494):
E/flutter (23494)

**Comment by thomassth** [comment]
Any particular action to trigger this error?
Don't know how to reproduce on my side

**Comment by SungHyun22** [comment]
All I did was run the app. There is no other trigger.

**Comment by thomassth** [comment]
Still no idea how to reproduce this.

Any details about your phone?
Did you see the "calendar permission" dialog?
Was the permission enabled within App Info?

**Comment by SungHyun22** [comment]
yes I acceppt all calendar permission but this error was occured.

**Comment by thomassth** [comment]
I've finally figured it out
Seems to be related to how Samsung make its local calendar (I happened to switch to a Samsung phone)
I'll try to open a branch with the fix, but perhaps someone else need to open the PR so that I can approve it.

**Comment by SungHyun22** [comment]
if I have a time i'll tryna fix it. thank you for figured out this problem.

**Comment by thomassth** [comment]
I've fixed the problem, see the branch I linked above
Problem is I need someone other than me to open a pull request, otherwise I'm not allowed to approve it.

**Comment by SungHyun22** [comment]
I can't open pull request

![image](https://user-images.githubusercontent.com/26302580/193803195-919c0d7f-efd1-4d84-8be6-ccc4450aeb24.png)

**Comment by thomassth** [comment]
I've no idea

Maybe try forking my branch, then do the PR? That way you don't have to write anything new

**Comment by SungHyun22** [comment]
I open the PR https://github.com/builttoroam/device_calendar/pull/443
