### ISSUE TITLE
support `timezone: 0.9.0`

### ISSUE THREAD

**Issue by IVLIVS-III** [builttoroam/device_calendar#437]
### Issue description

The `timezone` dependency is available in version `0.9.0` but cannot be used in projects that depend on `device_calendar: 4.2.0` because `device_calendar` depends on `timezone: ^0.8.0`.
Due to `timezone` being a `0.x.x` version, automatic version solving is treating the change in minor version number as a "breaking change" that is not allowed automatically.

### Steps to resolve this issue

- [x]  ensure `device_calendar` is compatible with `timezone: 0.9.0`. Compatibility should be given as long as `device_calendar` does not depend on named database files in `package:timezone/data` (for example, `package:timezone/data/2021e.tzf`), since the removal of those named files was the only breaking change from `timezone: 0.8.x` to `0.9.0`.
- [x]  update the `timezone` dependency in `pubspec.yaml` to `timezone: ^0.9.0`

**Comment by vixez** [comment]
I created a fork here meanwhile with a version bump. As I needed it for other packages

```
  device_calendar:
    git:
      url: https://github.com/vixez/device_calendar.git
      ref: develop
```

**Comment by thomassth** [comment]
Give me a PR and I'll push it through

I can't self push without other maintainers' approval, which all seems to be inactive.

**Comment by IVLIVS-III** [comment]
@thomassth PR has been created, thx for your efforts in keeping this plugin alive.
