### ISSUE TITLE
When will 4.2.1 be released?

### ISSUE THREAD

**Issue by mpszczolinski** [builttoroam/device_calendar#459]
Last release (4.2.0) was done in Feb 2022. I see that version 4.2.1 has some useful improvements.

When 4.2.1 will be released? Or did the author abandoned this project?

**Comment by IVLIVS-III** [comment]
Currently all (old and new) maintainers are short on time, unfortunately.
[This PR](https://github.com/builttoroam/device_calendar/pull/445) tracks the new release.

However I cannot give an ETA right now.


@thomassth what is missing until we can finalize the 5.0 pre-release? As far as I can see, only rrule-stuff is missing (#445 / #446 / #448).

**Comment by mpszczolinski** [comment]
Thanks IVLIVS-III for the answer.

Howevere you mentioned v.5, which sounds like big improvement. What about 4.2.1 itself?

**Comment by IVLIVS-III** [comment]
@mpszczolinski afaik v4.2.1 was never planned to be released / was never planned to be a standalone version in the first place.

Everything mentioned in the changelog was (prematurely) added to the changelog in (this PR)[https://github.com/builttoroam/device_calendar/pull/440] (by myself).
At the time of submitting the PR, I did not know what the next planned version number would be, thus listed the changes as a patch.

You could however pin the `device_calendar` dependency to that specific commit (hash) in your `pubspec.yaml` until the next version (v5.0) is released to pub.dev.

**Comment by thomassth** [comment]
I think it's fair to cheerypick commits other than rrule into a 4.2.1 or 4.3

... if someone can do that PR that is

**Comment by IVLIVS-III** [comment]
@thomassth cherry-picks for 4.3.0 are ready for review on #461. Merging to release automatically published to pub.dev, right?

**Comment by thomassth** [comment]
oof the cred seems to be expired

need @nickrandolph on that

**Comment by nickrandolph** [comment]
@thomassth I've updated the secrets. Can you give publishing a go and let me know if there are still issues

**Comment by thomassth** [comment]
Luckily we got `workflow_dispatch` for this scenario

No extra commit needed 😎
