### ISSUE TITLE
Upgrade timezone dependency from 0.8.0 to 0.9.0

### ISSUE THREAD

**Issue by techwnn** [builttoroam/device_calendar#460]
I noticed that [timezone 0.9.0](https://pub.flutter-io.cn/packages/timezone/changelog) published 2 months ago, I'm using another plugin named: flutter_local_notifications which also use timezone, currently I need use dependency_overrides to force timezone 0.9.0.

**Comment by thomassth** [comment]
already in the pipeline. See #459
