### ISSUE TITLE
Android build is failed for Kotlin 1.7.10 because of enum switch in 4.3.0 version

### ISSUE THREAD

**Issue by KostyaRolique** [builttoroam/device_calendar#470]
Flutter build is failed with this error:
`/opt/homebrew/Caskroom/flutter/3.3.4/flutter/.pub-cache/hosted/pub.dartlang.org/device_calendar-4.3.0/android/src/main/kotlin/com/builttoroam/devicecalendar/CalendarDelegate.kt: (784, 9): ‘when’ expression must be exhaustive, add necessary ‘DAILY’, ‘HOURLY’, ‘MINUTELY’, ‘SECONDLY’ branches or ‘else’ branch instead
`

During the research I found out that android source code for release `4.3.0` isn't published (especially the file `CalendarDelegate.kt`):
https://github.com/builttoroam/device_calendar/releases/tag/4.3.0
https://pub.dev/packages/device_calendar/versions

**Comment by felix9ia** [comment]
Looks like we'll just have to wait for the 5.0 release
Do you have any other way to temporarily solve this problem, can downgrading koltlin solve it

**Comment by thomassth** [comment]
I think this deserves a .1 release

Will approve if someone can make it

**Comment by hichaudh** [comment]
any ideas on when the pub release of 4.3.1 might occur?

**Comment by IVLIVS-III** [comment]
@hichaudh the prerelease version [4.3.1-4217521123](https://pub.dev/packages/device_calendar/versions/4.3.1-4217521123) is already released and available on [pub.dev](https://pub.dev/packages/device_calendar/versions/4.3.1-4217521123).
The full release of 4.3.1 should occur about 1-2 weeks after the prerelease, i.e. within 4-11 days.

**Comment by IVLIVS-III** [comment]
@thomassth it has been almost 3 weeks since the pre-release and no issues have been reported. Can we release version 4.3.1?
