### ISSUE TITLE
Obsolete flutter_native_timezone dependency in feat/macos-support branch

### ISSUE THREAD

**Issue by ash80** [builttoroam/device_calendar#474]
**Describe the bug**
flutter_native_timezone has become stale. It has been removed on develop branch but was brought back in feat/macos-support. flutter_native_timezone uses the kotlin version that is no longer supported by more recent kotlin plugin that comes with Android Studio. Hence I can't build or run the app using device_calendar on Android

**To Reproduce**
Compare the pubspec.yaml files on these branches.

**Expected behavior**
flutter_native_timezone should be removed from feat/macos-support as well.

**Device(s) tested**
This can be very important as not all device vendors do calendar in the same way.
 - OS: Android

**Comment by IVLIVS-III** [comment]
Thank you @ash80. I missed this when creating the feature branch.
It is removed now.

**Comment by IVLIVS-III** [comment]
In case you still cannot build or run the app on Android, please reply here and I will open the issue again.

**Comment by ash80** [comment]
Built successfully! Thanks

**Comment by DanilKarasev** [comment]
@IVLIVS-III Hey, device_calendar [4.3.1-4217521123] still fetching flutter_native_timezone. Am I doing something wrong?

**Comment by IVLIVS-III** [comment]
@DanilKarasev as far as I see, `flutter_native_timezone` has only been removed in the develop branch and any other branch based on develop, (e.g.: feat/macos-support).
It is still listed as a dependency in the release branch.
Hence it is downloaded when you depend on any (pre-)releases from pub.dev.

I guess it will be removed when publishing version 5.0 of `device_calendar`.

**Comment by DanilKarasev** [comment]
@IVLIVS-III Thanks! Then I guess only option now is to clone repo and use it as local package as of now.

**Comment by thomassth** [comment]
While all new stuff should go to 5.x now, I feel we should at least keep 4.X usable and vulnerability free (without too much effort)

So 4.3.2 perhaps?

**Comment by agacemi** [comment]
Any idea when this can be released ?

**Comment by bardram** [comment]
Same problem here. 

Could you publish a version `4.4.0` or similar that uses `flutter_timezone` instead of the stale `flutter_native_timezone`?

Thanks.

**Comment by IVLIVS-III** [comment]
All maintainers are ob a really low time-budget at the moment. Please provide a pull request, that addresses your concern.
This will be the fastest way to get this issue fixed.
