### ISSUE TITLE
ios flutter: PlatformException(401, The user has not allowed this application to modify their calendar(s), null, null)

### ISSUE THREAD

**Issue by FangPro** [builttoroam/device_calendar#485]
I ran my program on the iOS simulator, but this error occurred

flutter: PlatformException(401, The user has not allowed this application to modify their calendar(s), null, null)

This is my code:
`void createAlarmCalendar({required ScheduleModel model}) async{
    var hasPermissions = await DeviceCalendarPlugin().hasPermissions();
    if(hasPermissions.isSuccess){
      _createEvent(model: model);
    } else {
      await DeviceCalendarPlugin().requestPermissions().then((result){
        if(result.isSuccess){
          _createEvent(model: model);
        }
      });
    }
  }

  _createEvent({required ScheduleModel model}) async{
    await DeviceCalendarPlugin().createOrUpdateEvent(Event(
      calenderId,
      eventId: model.id!,
      title: "${model.course!}直播课",
      start: TZDateTime.fromMillisecondsSinceEpoch(tz.local, model.liveStart!),
      end: TZDateTime.fromMillisecondsSinceEpoch(tz.local, model.liveEnd!),
      availability: Availability.Free,
      attendees: [],
      allDay: false,
      status: EventStatus.Tentative,
      location: tz.local.name,
      reminders: [],
    )).then((result){
      if(result!.data!=null&&result.data!=""){
        debugPrint(result.data!);
        isCalendars = true;
        StorageManage.sp!.setString(model.id!, result.data!);
        bus.emit("REFRESH_CALENDAR");
        ToastUtil.showText("当前直播提醒已开启");
        notifyListeners();
      } else {
        ToastUtil.showText("当前直播提醒开启失败");
      }
    });
  }`

**Comment by IVLIVS-III** [comment]
@FangPro have you checked that the calendar you are trying to modify is **not** readonly?

**Comment by IVLIVS-III** [comment]
This line seems to be wrong as well:

```dart
if(result!.data!=null&&result.data!="")
```

having the `!` after `result!.data!` makes sure that `result` as well as `result.data` are never `null`. If it were `null`, it would crash the app. So checking `result!.data! == null` is either `true` or your app crashes.
You also used a single `=` instead of a double `==` which doesn't do what I think you are trying to do. Equality is checked using double `==`.

**Comment by FangPro** [comment]
This is the calendar on the iOS simulator. What additional information do I need to provide

**Comment by IVLIVS-III** [comment]
well, when calling `retrieveCalendars`, how many calendars are returned?

**Comment by IVLIVS-III** [comment]
Did you follow the [steps to integrate iOS](https://pub.dev/packages/device_calendar#ios-integration)?

**Comment by FangPro** [comment]
Step configuration for integrating iOS:
`<key>NSCalendarsUsageDescription</key>
<string>Access most functions for calendar viewing and editing.</string>

<key>NSContactsUsageDescription</key>
<string>Access contacts for event attendee editing.</string>`
Do I need any additional configurations?

**Comment by FangPro** [comment]
Hello author, it's my problem. I have summarized the following reasons:
1. Before creating an event on iOS, it is necessary to directly request permissions, rather than first determining whether permissions exist
2. Before creating an event, you need to traverse and query the calendar to obtain a specified calendar ID
3. In the creation event method parameters, do not specify the event ID yourself. The callback method for creating the event will help us return
The above is what I have found to be worth noting. Thank you to the plugin author.

**Comment by mbcHans** [comment]
> Hello author, it's my problem. I have summarized the following reasons:
> 
> 1. Before creating an event on iOS, it is necessary to directly request permissions, rather than first determining whether permissions exist
> 2. Before creating an event, you need to traverse and query the calendar to obtain a specified calendar ID
> 3. In the creation event method parameters, do not specify the event ID yourself. The callback method for creating the event will help us return
>    The above is what I have found to be worth noting. Thank you to the plugin author.

Hi, how did you solve this issue? I meet this problem too.

**Comment by FangPro** [comment]
Have you encountered the same error message? On which platform, Android or iOS?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "builttoroam/device_calendar"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月17日(星期三) 下午5:16
***@***.***&gt;;
抄送:&nbsp;"Billows Bear ***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [builttoroam/device_calendar] ios flutter: PlatformException(401, The user has not allowed this application to modify their calendar(s), null, null) (Issue #485)





  
Hello author, it's my problem. I have summarized the following reasons:
  
Before creating an event on iOS, it is necessary to directly request permissions, rather than first determining whether permissions exist
 
Before creating an event, you need to traverse and query the calendar to obtain a specified calendar ID
 
In the creation event method parameters, do not specify the event ID yourself. The callback method for creating the event will help us return
 The above is what I have found to be worth noting. Thank you to the plugin author.
   
Hi, how did you solve this issue? I meet this problem too.

**Comment by mbcHans** [comment]
> Hello author, it's my problem. I have summarized the following reasons: Before creating an event on iOS, it is necessary to directly request permissions, rather than first determining whether permissions exist Before creating an event, you need to traverse and query the calendar to obtain a specified calendar ID In the creation event method parameters, do not specify the event ID yourself. The callback method for creating the event will help us return The above is what I have found to be worth noting. Thank you to the plugin author. Hi, how did you solve this issue? I meet this problem too.

Yes, same error log happened on iOS platform.

**Comment by FangPro** [comment]
Have you applied for permission before creating a subscription event,Then you can take a look at my code below：


_createEvent({required ScheduleModel model}) async{
&nbsp; &nbsp; var currentLocation = getLocation(await FlutterNativeTimezone.getLocalTimezone());
&nbsp; &nbsp; setLocalLocation(currentLocation);
&nbsp; &nbsp; await DeviceCalendarPlugin().retrieveCalendars().then((list) async{
&nbsp; &nbsp; &nbsp; if(list.data!.isNotEmpty){
&nbsp; &nbsp; &nbsp; &nbsp; for(var v in list.data!){
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; debugPrint("name===&gt;${v.name!}");
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; debugPrint("id===&gt;${v.id!}");
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; debugPrint("accountName===&gt;${v.accountName!}");
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; debugPrint("accountType===&gt;${v.accountType!}");
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; debugPrint("isReadOnly===&gt;${v.isReadOnly!}");
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; debugPrint("isDefault===&gt;${v.isDefault!}");
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; if(v.isDefault! &amp;&amp; !v.isReadOnly!){
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; calenderId = v.id!;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; } else if(v.accountType == "LOCAL"){
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; calenderId = v.id!;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; debugPrint("calenderId--------------&gt;$calenderId");
&nbsp; &nbsp; &nbsp; await DeviceCalendarPlugin().createOrUpdateEvent(Event(
&nbsp; &nbsp; &nbsp; &nbsp; calenderId,
&nbsp; &nbsp; &nbsp; &nbsp; title: "${model.course!}直播课",
&nbsp; &nbsp; &nbsp; &nbsp; start: TZDateTime.fromMillisecondsSinceEpoch(currentLocation, model.liveStart!),
&nbsp; &nbsp; &nbsp; &nbsp; end: TZDateTime.fromMillisecondsSinceEpoch(currentLocation, model.liveEnd!),
&nbsp; &nbsp; &nbsp; &nbsp; availability: Availability.Free,
&nbsp; &nbsp; &nbsp; &nbsp; attendees: [],
&nbsp; &nbsp; &nbsp; &nbsp; allDay: false,
&nbsp; &nbsp; &nbsp; &nbsp; status: EventStatus.Confirmed,
&nbsp; &nbsp; &nbsp; &nbsp; location: currentLocation.name,
&nbsp; &nbsp; &nbsp; &nbsp; reminders: [
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Reminder(minutes: 60),
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Reminder(minutes: 30),
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Reminder(minutes: 10),
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Reminder(minutes: 5),
&nbsp; &nbsp; &nbsp; &nbsp; ],
&nbsp; &nbsp; &nbsp; )).then((result){
&nbsp; &nbsp; &nbsp; &nbsp; if(result!.data!=null &amp;&amp; result.data !=""){
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; debugPrint(result.data);
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; isCalendars = true;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; StorageManage.sp!.setString(model.id!, result.data!);
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; bus.emit("REFRESH_CALENDAR");
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ToastUtil.showText("当前直播提醒已开启");
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; notifyListeners();
&nbsp; &nbsp; &nbsp; &nbsp; } else {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ToastUtil.showText("当前直播提醒开启失败");
&nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; });
&nbsp; &nbsp; });
&nbsp; }





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "builttoroam/device_calendar"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月18日(星期四) 上午9:34
***@***.***&gt;;
抄送:&nbsp;"Billows Bear ***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [builttoroam/device_calendar] ios flutter: PlatformException(401, The user has not allowed this application to modify their calendar(s), null, null) (Issue #485)





  
Hello author, it's my problem. I have summarized the following reasons: Before creating an event on iOS, it is necessary to directly request permissions, rather than first determining whether permissions exist Before creating an event, you need to traverse and query the calendar to obtain a specified calendar ID In the creation event method parameters, do not specify the event ID yourself. The callback method for creating the event will help us return The above is what I have found to be worth noting. Thank you to the plugin author. Hi, how did you solve this issue? I meet this problem too.
  
Yes, same error log happened on iOS platform.
