### ISSUE TITLE
Wrong Timezone 

### ISSUE THREAD

**Issue by tungakanui** [builttoroam/device_calendar#506]
**Describe the bug**
I added an event with the timezone Europe/Berlin, it should be GMT+2 (cause it's summer now) instead of GMT+1

**To Reproduce**
Step 1: Add an event with the timezone of 'Europe/Berlin'
Step 2: Check the result

**Expected behavior**
It should get the correct timezone.

**Screenshots**
![image](https://github.com/builttoroam/device_calendar/assets/54916679/653aa527-5692-45c2-b1d6-2630bcebb222)

**Device(s) tested**
This can be very important as not all device vendors do calendar in the same way.
 - Device: iPhone XS
 - OS: ios 16
 - Plugin version: 4.3.1 

**Flutter doctor**
Run a `flutter doctor` so we can rule out env issues

**Comment by info-trone** [comment]
Could you provide some code of how you load/use the timezone and what package you are using?

**Comment by laminr** [comment]
Humm Gulfsteam G-IV, so nice!

**Comment by tungakanui** [comment]
> Could you provide some code of how you load/use the timezone and what package you are using?
Here's the code I'm using.
The package: device_calendar: ^4.3.1
`  final Event event = Event(
      calendarID,
      eventId: eventID,
      title: eventTitle,
      description: eventDescription,
      location: eventLocation,
      start: TZDateTime(
        getLocation(departureTimeZone),
        eventStartDate.year,
        eventStartDate.month,
        eventStartDate.day,
        eventStartDate.hour,
        eventStartDate.minute,
        eventStartDate.second,
      ),
      end: TZDateTime(
        getLocation(arrivalTimeZone),
        eventEndDate.year,
        eventEndDate.month,
        eventEndDate.day,
        eventEndDate.hour,
        eventEndDate.minute,
        eventEndDate.second,
      ),
    );

    return _deviceCalendarPlugin.createOrUpdateEvent(event);`

**Comment by tungakanui** [comment]
I apologize. It's my mistake. I tried to convert time of 1/11, at that time the correct timezone is GMT+1.
