### ISSUE TITLE
Calendar permission not showing

### ISSUE THREAD

**Issue by info-trone** [builttoroam/device_calendar#507]
**Describe the bug**
After adding all requirements for the package(info.plist, pod spec gcc settings, example code), im not getting a prompt nor am I seeing the setting in the app settings. This package has worked before IOS 17, I wonder if that could be the issue. I tried creating a new project only using this package and example code, but can't seem to get it to work. 

**To Reproduce**
1. Start a new flutter project
2. add single page with the example code, info.plist permissions, add the pod spec build settings
3. startup the project and check if the calendars are being retrieved (print/debug)

**Expected behavior**
Calendar permission to use the package. with the prompt necessary to give it

**Device(s) tested**
 - Device: Device - 12 mini, Emulator - 15 pro max, SE
 - OS: IOS 17
 - Plugin version 4.3.1 (using a custom commit for the native timezone compatibility with a new Kotlin version - url: https://github.com/builttoroam/device_calendar.git)

**Flutter doctor**
![image](https://github.com/builttoroam/device_calendar/assets/142014588/de028cd9-9011-4ee8-bb9f-32c4bd60953a)

**Additional context**
I read through he ios17 notes and found this under privacy: "Improved sharing permissions give you even more control over what you share with apps, with an embedded photo picker and an add-only Calendar permission" could be applicable? im not sure

Also the permission_handler package won't give me a prompt for calendar permissions, but it will with other permissions

**Comment by info-trone** [comment]
Did some more searching, as seen in these issues from the permission_handler package. iOS 17 has indeed changed it's calendar permission and some additions will be needed to make this package work.

- https://github.com/Baseflow/flutter-permission-handler/pull/1151
- https://github.com/Baseflow/flutter-permission-handler/issues/1108

**Comment by info-trone** [comment]
Did some more searching, as seen in these issues from the permission_handler package. iOS 17 has indeed changed it's calendar permission and some additions will be needed to make this package work.

https://github.com/Baseflow/flutter-permission-handler/pull/1151
https://github.com/Baseflow/flutter-permission-handler/issues/1108

**Comment by henry2man** [comment]
Here it is some additional info that may be useful: https://developer.apple.com/documentation/eventkit/accessing_calendar_using_eventkit_and_eventkitui

**Comment by Quentinio** [comment]
I tried changing the pod file as recommended with iOS 17 but still wasn't able to call the permissions dialog. My current work around was by invoking it from appdelegate.swift
    final String status = await platform.invokeMethod('checkCalendarAuthorizationStatus');

**Comment by Dassine** [comment]
I have the same issue. we should reopen this thread. Thanks for your help.
