### ISSUE TITLE
[4.3.2] Google Account calendar events do not load

### ISSUE THREAD

**Issue by yarmel** [builttoroam/device_calendar#524]
When I add a Google account calendar to my macOS and add an event, this event does not load when I try to load it in my app.

```
dc.Result<UnmodifiableListView<dc.Event>> events = await plugin
       .retrieveEvents(
         cid,
         dc.RetrieveEventsParams(
           startDate: from,
           endDate: to,
         ),
       )
```
events.data returns an empty array. However, default IOS calendars fetch events correctly. Also, I can add events to my Google calendar. The problem only pertains to retrieving events from connected Google calendars.

! develop branch does not contain this bug, only version 4.3.2

**Comment by Velliane** [comment]
Hi ! I have the same problem.
Does anyone have a solution ? 
(I try return to 4.3.1, but I encounterer problem with flutter_native_timezone package...)

**Comment by yarmel** [comment]
> Hi ! I have the same problem. Does anyone have a solution ? (I try return to 4.3.1, but I encountered problem with flutter_native_timezone package...)

Seems that this package support runs with the extra lowest priority. Bugs are not fixed. And no response from the developer for more than 2 weeks. So this thread can be closed, as I completely removed this package and rewrote it all to work with Google Calendar directly. Not it works perfectly :).
