### ISSUE TITLE
New release whit support for IOS 17+ and android 14 (API 34)

### ISSUE THREAD

**Issue by Peng1104** [builttoroam/device_calendar#527]
The lasted release (4.3.2) was done in Nov 2024. 
But on this release the support for IOS 17+ and Android 14 (API 34) that need android Gradle plugin version 8+ was not added. Is there any prevision for when a release will have this features? I have seen that the develop branch has already fixed this issues.

**Comment by Peng1104** [comment]
#523 Is a example of this problem

**Comment by istornz** [comment]
iOS 17+ support is underway and should be available soon with a new pub.dev release #519

**Comment by Peng1104** [comment]
> iOS 17+ support is underway and should be available soon with a new pub.dev release #519

In this PR the "namespace" key to add the support for the AGP 8.0+ is still missing

**Comment by istornz** [comment]
At this time iOS 17+& Android 14+ fixs are now merged 👍 
@thomassth Do you have some ETA when the new version/build will be published on pub.dev?

Thanks a lot 🥇

**Comment by Albert221** [comment]
@thomassth hey! just a friendly ping. The iOS 17+ support is already merged, we just wait for the release :)

**Comment by UshaBrillio** [comment]
@thomassth any ETA for iOS 17+ support

**Comment by istornz** [comment]
Bump, is there is any news? If not, maybe we can create a fork?

**Comment by thomassth** [comment]
Try out the 4.3.3 prerelease, the fixes should be there
