### ISSUE TITLE
Unable to add events on both ios and android.

### ISSUE THREAD

**Issue by akshykalia** [builttoroam/device_calendar#538]
**Describe the bug**
In a few sentence, briefly describe of what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**
Optional, add screenshots if it helps explain your problem.

**Device(s) tested**
This can be very important as not all device vendors do calendar in the same way.
 - Device: [e.g. Pixel 6]
 - OS: [e.g. Android 12.0]
 - Plugin version [e.g. 4.2.0 Release]

**Flutter doctor**
Run a `flutter doctor` so we can rule out env issues

**Additional context**

**Comment by thomassth** [comment]
Not enough information.
