### ISSUE TITLE
The event with the ID could not be found.

### ISSUE THREAD

**Issue by michalcharvat** [builttoroam/device_calendar#555]
**Describe the bug**
Compared to other similar issues this is about updating existing event that was created few minutes ago. 

**To Reproduce**
1. Create event by using createOrUpdateEvent
2. Store eventId somewhere
3. Change the event start/endDate and call createOrUpdateEvent with eventId
4. See error PlatformException(404, The event with the ID x-y-z could not be found, null, null)

**Device(s) tested**
This can be very important as not all device vendors do calendar in the same way.
 - Device: iOS Simulator
 - OS: iOS 17.5
 - Plugin version 4.3.2

**Flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale en-CZ)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.91.1)
[✓] Connected device (4 available)
[✓] Network resources

**Comment by michalcharvat** [comment]
However, the error is set very randomly. Everything looks OK and then one of the x events is duplicated. If I use retrieveEvents on a short range +-7 days the event is missing at error 599 (createEventResult.errors.first.errorCode).

**Comment by Jonny5-5** [comment]
### I'm experiencing this issue as well

I have been researching a way to store event ids so I can edit the calendar event at a later date. I found this documentation on Apple Developer [website](https://developer.apple.com/documentation/eventkit/ekevent/1507437-eventidentifier) 
##### "If the calendar of an event changes, its identifier most likely changes as well."

So I'm curious if the calendar event ids are subject to change at any time? If I edit the task in Google Calendar, for example, will the Event id sometimes change?

**Comment by thomassth** [comment]
If Apple's not providing consistent event ID then neither can we. 

As always you can write your own logic to workaround this issue, but ATM this is out of scope of this extension.
